/* ===========================
   SmartStudy MCQ - bank.js
   20 Topics • 30 Questions Each
   Format:
   { q: "Question", options: ["A","B","C","D"], ans: 0-3 }
   =========================== */

"use strict";

window.QUESTION_BANK = {

  "Physics (Basics)": [
    { q:"SI unit of force is:", options:["Watt","Pascal","Newton","Joule"], ans:2 },
    { q:"Speed is defined as:", options:["Distance ÷ Time","Time ÷ Distance","Mass × Acceleration","Work ÷ Time"], ans:0 },
    { q:"Which is a vector quantity?", options:["Speed","Mass","Velocity","Temperature"], ans:2 },
    { q:"SI unit of work is:", options:["Newton","Joule","Watt","Pascal"], ans:1 },
    { q:"Acceleration is change in:", options:["Distance","Velocity","Mass","Time"], ans:1 },
    { q:"A device used to measure electric current:", options:["Voltmeter","Ammeter","Barometer","Thermometer"], ans:1 },
    { q:"Unit of power is:", options:["Joule","Watt","Newton","Pascal"], ans:1 },
    { q:"Which is NOT a renewable energy source?", options:["Solar","Wind","Coal","Hydro"], ans:2 },
    { q:"Density =", options:["Mass ÷ Volume","Volume ÷ Mass","Force ÷ Area","Work ÷ Time"], ans:0 },
    { q:"Pressure SI unit:", options:["Watt","Pascal","Joule","Newton"], ans:1 },
    { q:"Sound needs ______ to travel.", options:["Vacuum","Medium","Light","Magnet"], ans:1 },
    { q:"Speed of light is approximately:", options:["3×10^8 m/s","3×10^6 m/s","3×10^4 m/s","3×10^2 m/s"], ans:0 },
    { q:"Which mirror can form a real image?", options:["Plane mirror","Concave mirror","Convex mirror","No mirror"], ans:1 },
    { q:"Lens used for myopia (short-sight):", options:["Convex lens","Concave lens","Plane lens","No lens"], ans:1 },
    { q:"The unit of frequency:", options:["Hertz","Newton","Joule","Volt"], ans:0 },
    { q:"Electric potential difference is measured by:", options:["Ammeter","Voltmeter","Galvanometer","Compass"], ans:1 },
    { q:"Ohm’s law relates:", options:["V, I, R","P, V, T","F, m, a","E, m, c"], ans:0 },
    { q:"1 kWh equals:", options:["3.6×10^6 J","3.6×10^3 J","3.6×10^9 J","36 J"], ans:0 },
    { q:"Friction acts:", options:["Same as motion","Opposite to motion","Perpendicular only","Random"], ans:1 },
    { q:"Mass is measured in:", options:["Newton","Kilogram","Joule","Watt"], ans:1 },
    { q:"Weight depends on:", options:["Mass only","Gravity only","Mass and gravity","Volume"], ans:2 },
    { q:"SI unit of charge:", options:["Coulomb","Volt","Ohm","Watt"], ans:0 },
    { q:"A good conductor is:", options:["Rubber","Copper","Glass","Plastic"], ans:1 },
    { q:"Transformer works on:", options:["DC","AC","Both DC and AC","Neither"], ans:1 },
    { q:"Which has highest resistivity?", options:["Copper","Aluminium","Glass","Silver"], ans:2 },
    { q:"Magnetic field lines emerge from:", options:["South pole","North pole","Center","Both poles"], ans:1 },
    { q:"Unit of temperature (SI):", options:["Kelvin","Newton","Pascal","Volt"], ans:0 },
    { q:"Heat transfer without medium is:", options:["Conduction","Convection","Radiation","Friction"], ans:2 },
    { q:"Boiling point of water (1 atm):", options:["0°C","50°C","100°C","212°C"], ans:2 }
  ],

  "Chemistry (Basics)": [
    { q:"Acids turn which litmus red?", options:["Red","Blue","Green","Yellow"], ans:1 },
    { q:"pH less than 7 indicates:", options:["Base","Salt","Acid","Neutral"], ans:2 },
    { q:"Common salt formula:", options:["NaCl","KCl","HCl","NaOH"], ans:0 },
    { q:"Water chemical formula:", options:["H2O","CO2","O2","H2"], ans:0 },
    { q:"Atomic number represents:", options:["Neutrons","Protons","Electrons only","Mass number"], ans:1 },
    { q:"A base turns red litmus:", options:["Red","Blue","Green","No change"], ans:1 },
    { q:"Substance with pH 7 is:", options:["Acidic","Basic","Neutral","Salt only"], ans:2 },
    { q:"Rusting is an example of:", options:["Reduction","Oxidation","Neutralization","Sublimation"], ans:1 },
    { q:"Chemical symbol of Sodium:", options:["So","Na","S","No"], ans:1 },
    { q:"Chemical symbol of Potassium:", options:["P","Pt","K","Po"], ans:2 },
    { q:"Gas essential for combustion:", options:["Nitrogen","Oxygen","Hydrogen","Carbon dioxide"], ans:1 },
    { q:"CO2 is a:", options:["Acid","Basic oxide","Neutral oxide","Salt"], ans:1 },
    { q:"Metal + Acid produces:", options:["Salt + Water","Salt + Hydrogen","Sugar + Oxygen","Base + Water"], ans:1 },
    { q:"Which is an alkali?", options:["NaOH","HCl","NaCl","CO2"], ans:0 },
    { q:"The smallest particle of an element:", options:["Molecule","Atom","Compound","Mixture"], ans:1 },
    { q:"A homogeneous mixture is:", options:["Air","Sand+Water","Oil+Water","Soil"], ans:0 },
    { q:"Melting point is when solid:", options:["Becomes liquid","Becomes gas","Becomes plasma","Explodes"], ans:0 },
    { q:"Boiling point is when liquid:", options:["Becomes solid","Becomes gas","Becomes metal","Becomes salt"], ans:1 },
    { q:"Reaction releasing heat:", options:["Endothermic","Exothermic","Neutral","Ionic"], ans:1 },
    { q:"Lemon juice is:", options:["Acidic","Basic","Neutral","Salt"], ans:0 },
    { q:"Vinegar contains:", options:["HCl","Acetic acid","Nitric acid","Sulfuric acid"], ans:1 },
    { q:"Baking soda formula:", options:["Na2CO3","NaHCO3","KCl","CaCO3"], ans:1 },
    { q:"Washing soda formula:", options:["Na2CO3","NaHCO3","H2SO4","NaCl"], ans:0 },
    { q:"A catalyst:", options:["Changes products","Increases activation energy","Changes reaction speed","Stops reaction"], ans:2 },
    { q:"Neutralization forms:", options:["Salt + Water","Salt + Hydrogen","Acid + Base","Metal + Water"], ans:0 },
    { q:"Hydrogen is a:", options:["Metal","Non-metal","Noble gas","Liquid"], ans:1 },
    { q:"Oxygen is a:", options:["Metal","Non-metal","Alloy","Salt"], ans:1 },
    { q:"Noble gases are generally:", options:["Very reactive","Moderately reactive","Non-reactive","Always acidic"], ans:2 },
    { q:"A solution is:", options:["Pure substance","Solute + solvent mixture","Only solid","Only gas"], ans:1 },
    { q:"Evaporation happens at:", options:["Only boiling point","Any temperature","0°C only","100°C only"], ans:1 }
  ],

  "Mathematics (Algebra)": [
    { q:"If x + 5 = 12, x =", options:["5","6","7","8"], ans:2 },
    { q:"Simplify: 3×(4+2) =", options:["18","12","14","20"], ans:0 },
    { q:"Value of 2^5 =", options:["10","16","32","64"], ans:2 },
    { q:"If 2x = 18, x =", options:["7","8","9","10"], ans:2 },
    { q:"(a+b)^2 =", options:["a^2+b^2","a^2+2ab+b^2","a^2-ab+b^2","a^2+ab+b^2"], ans:1 },
    { q:"Factorize: x^2 - 9 =", options:["(x-9)(x+1)","(x-3)(x+3)","(x-3)^2","(x+9)(x-1)"], ans:1 },
    { q:"If y = 3x and x=4, y =", options:["7","10","12","15"], ans:2 },
    { q:"Solve: x/3 = 5", options:["10","12","15","18"], ans:2 },
    { q:"Simplify: 5a - 2a =", options:["7a","3a","3","a"], ans:1 },
    { q:"If a=2, b=3 then ab =", options:["5","6","8","9"], ans:1 },
    { q:"Solve: x - 9 = 0", options:["0","9","-9","1"], ans:1 },
    { q:"If 3x + 2 = 11, x =", options:["2","3","4","5"], ans:0 },
    { q:"(x+2)(x+3) =", options:["x^2+5x+6","x^2+6x+5","x^2+3x+2","x^2+2x+3"], ans:0 },
    { q:"If x^2=49, x can be:", options:["7 only","-7 only","7 or -7","0"], ans:2 },
    { q:"Linear equation has highest power:", options:["0","1","2","3"], ans:1 },
    { q:"Solve: 4x = 28", options:["5","6","7","8"], ans:2 },
    { q:"Simplify: x·x·x =", options:["3x","x^2","x^3","x/3"], ans:2 },
    { q:"If x=1, value of x^2 + 2x + 1 =", options:["1","2","3","4"], ans:3 },
    { q:"Solve: 2(x+3)=14", options:["2","3","4","5"], ans:2 },
    { q:"If x=0, 5x+7 =", options:["0","5","7","12"], ans:2 },
    { q:"Simplify: 9a/3 =", options:["a","2a","3a","6a"], ans:2 },
    { q:"If x=2, 3x^2 =", options:["6","9","12","18"], ans:2 },
    { q:"Factorize: x^2 + 5x =", options:["x(x+5)","(x+5)^2","x^2(5x)","(x-5)x"], ans:0 },
    { q:"If 5x=5, x =", options:["0","1","5","10"], ans:1 },
    { q:"Solve: x + x = 10", options:["2","4","5","10"], ans:2 },
    { q:"Solve: x/2 + 1 = 6", options:["8","10","12","14"], ans:0 },
    { q:"If a-b=2, a=5 then b=", options:["1","2","3","7"], ans:2 },
    { q:"Simplify: (2a)(3b) =", options:["5ab","6ab","6a+b","a6b"], ans:1 },
    { q:"If x=3, 2x+1 =", options:["5","6","7","8"], ans:2 },
    { q:"Solve: x - 4 = 9", options:["5","9","12","13"], ans:3 }
  ],

  "Mathematics (Geometry)": [
    { q:"Sum of angles in a triangle:", options:["90°","180°","270°","360°"], ans:1 },
    { q:"A right angle is:", options:["45°","90°","180°","360°"], ans:1 },
    { q:"A straight angle is:", options:["90°","180°","270°","360°"], ans:1 },
    { q:"A circle has how many degrees?", options:["90°","180°","270°","360°"], ans:3 },
    { q:"Perimeter of a rectangle:", options:["l×b","2(l+b)","l+b","l^2"], ans:1 },
    { q:"Area of a rectangle:", options:["l×b","2(l+b)","l+b","l^2"], ans:0 },
    { q:"Area of a triangle:", options:["b×h","(b×h)/2","2(b+h)","b+h"], ans:1 },
    { q:"A square has:", options:["2 equal sides","4 equal sides","No equal sides","3 equal sides"], ans:1 },
    { q:"Angle in a semicircle is:", options:["45°","60°","90°","180°"], ans:2 },
    { q:"A quadrilateral has ____ sides.", options:["3","4","5","6"], ans:1 },
    { q:"Sum of angles in a quadrilateral:", options:["180°","270°","360°","540°"], ans:2 },
    { q:"Radius is:", options:["Diameter/2","2×Diameter","Diameter+1","None"], ans:0 },
    { q:"Diameter is:", options:["Radius/2","2×Radius","Radius+π","None"], ans:1 },
    { q:"Circumference of circle:", options:["πr^2","2πr","πd^2","r^2"], ans:1 },
    { q:"Area of circle:", options:["2πr","πr^2","πd","r^2"], ans:1 },
    { q:"A line segment has:", options:["One endpoint","Two endpoints","No endpoints","Infinite endpoints"], ans:1 },
    { q:"A ray has:", options:["Two endpoints","One endpoint","No endpoint","Three endpoints"], ans:1 },
    { q:"An obtuse angle is:", options:["<90°","=90°",">90° and <180°",">180°"], ans:2 },
    { q:"An acute angle is:", options:["<90°","=90°",">90°","=180°"], ans:0 },
    { q:"Parallel lines:", options:["Meet at one point","Never meet","Always perpendicular","Always same line"], ans:1 },
    { q:"Perpendicular lines intersect at:", options:["45°","90°","180°","360°"], ans:1 },
    { q:"A cube has ____ faces.", options:["4","5","6","8"], ans:2 },
    { q:"A cube has ____ edges.", options:["8","10","12","14"], ans:2 },
    { q:"A cube has ____ vertices.", options:["6","8","10","12"], ans:1 },
    { q:"Volume of a cube:", options:["a^2","a^3","2a","6a"], ans:1 },
    { q:"Area of a square:", options:["4a","a^2","2a","a^3"], ans:1 },
    { q:"Rectangle has opposite sides:", options:["Unequal","Equal","3 equal","None"], ans:1 },
    { q:"Triangle with all sides equal:", options:["Scalene","Isosceles","Equilateral","Right"], ans:2 },
    { q:"Triangle with two sides equal:", options:["Scalene","Isosceles","Equilateral","Obtuse"], ans:1 },
    { q:"Triangle with all sides different:", options:["Scalene","Isosceles","Equilateral","Right"], ans:0 }
  ],

  "Biology (Human Body)": [
    { q:"Main organ for pumping blood:", options:["Lungs","Heart","Brain","Kidney"], ans:1 },
    { q:"Largest organ in human body:", options:["Heart","Skin","Liver","Lungs"], ans:1 },
    { q:"Unit of nervous system is:", options:["Neuron","Cell wall","RBC","Platelet"], ans:0 },
    { q:"Organ used for breathing:", options:["Stomach","Lungs","Liver","Pancreas"], ans:1 },
    { q:"Blood carries oxygen using:", options:["Platelets","WBC","RBC","Plasma"], ans:2 },
    { q:"Vitamin made in sunlight:", options:["Vitamin A","Vitamin B","Vitamin C","Vitamin D"], ans:3 },
    { q:"Food pipe is called:", options:["Trachea","Esophagus","Bronchus","Ureter"], ans:1 },
    { q:"Part that controls body activities:", options:["Heart","Brain","Lungs","Skin"], ans:1 },
    { q:"Kidneys help in:", options:["Breathing","Excretion","Digestion","Circulation"], ans:1 },
    { q:"Bones provide:", options:["Support and protection","Oxygen","Food","Hormones"], ans:0 },
    { q:"Stomach mainly helps in:", options:["Breathing","Digestion","Hearing","Vision"], ans:1 },
    { q:"Enzyme in saliva:", options:["Pepsin","Amylase","Lipase","Trypsin"], ans:1 },
    { q:"Normal body temperature:", options:["35°C","37°C","39°C","41°C"], ans:1 },
    { q:"Pulse is linked to:", options:["Breathing rate","Heart rate","Digestion","Vision"], ans:1 },
    { q:"WBC helps in:", options:["Oxygen transport","Fighting infection","Clotting","Digestion"], ans:1 },
    { q:"Platelets help in:", options:["Clotting","Breathing","Hearing","Vision"], ans:0 },
    { q:"Small intestine mainly absorbs:", options:["Oxygen","Nutrients","Urine","Blood"], ans:1 },
    { q:"Bile is produced by:", options:["Stomach","Liver","Pancreas","Kidney"], ans:1 },
    { q:"Insulin is produced by:", options:["Liver","Pancreas","Heart","Lungs"], ans:1 },
    { q:"Brain is protected by:", options:["Ribs","Skull","Spine","Pelvis"], ans:1 },
    { q:"Spinal cord is part of:", options:["Digestive","Nervous","Respiratory","Endocrine"], ans:1 },
    { q:"Main function of lungs:", options:["Pump blood","Exchange gases","Produce bile","Filter blood"], ans:1 },
    { q:"Blood vessels carrying blood away from heart:", options:["Veins","Arteries","Capillaries","Nerves"], ans:1 },
    { q:"Blood vessels carrying blood to heart:", options:["Veins","Arteries","Capillaries","Alveoli"], ans:0 },
    { q:"Gas exchange happens at:", options:["Nephrons","Alveoli","Villi","Atrium"], ans:1 },
    { q:"Eye lens helps in:", options:["Hearing","Focusing light","Pumping blood","Digestion"], ans:1 },
    { q:"Ear part for balance:", options:["Cochlea","Pinna","Semicircular canals","Eardrum"], ans:2 },
    { q:"Teeth help in:", options:["Breathing","Chewing","Pumping","Filtering"], ans:1 },
    { q:"Ribs protect:", options:["Brain","Heart and lungs","Kidneys only","Stomach only"], ans:1 },
    { q:"Main excretory product in humans:", options:["Oxygen","Urea","Glucose","Protein"], ans:1 }
  ],

  "Computer Science (Basics)": [
    { q:"CPU stands for:", options:["Central Power Unit","Central Processing Unit","Computer Processing Unit","Core Processing Unit"], ans:1 },
    { q:"RAM is:", options:["Permanent memory","Temporary memory","A software","A network"], ans:1 },
    { q:"ROM is:", options:["Temporary memory","Permanent memory","Cache","Register"], ans:1 },
    { q:"Binary system uses:", options:["0-9","0 and 1","1-8","A-Z"], ans:1 },
    { q:"1 byte =", options:["4 bits","8 bits","16 bits","32 bits"], ans:1 },
    { q:"An OS example:", options:["Chrome","Windows","Python","HTML"], ans:1 },
    { q:"Browser example:", options:["Linux","Google Chrome","C++","MySQL"], ans:1 },
    { q:"HTML is used for:", options:["Styling","Structure","Database","Virus"], ans:1 },
    { q:"CSS is used for:", options:["Structure","Styling","Server","Compiler"], ans:1 },
    { q:"JavaScript is mainly used for:", options:["Paint","Interactivity","Printing","Charging"], ans:1 },
    { q:"A loop is used to:", options:["Stop program","Repeat tasks","Store images","Format disk"], ans:1 },
    { q:"An algorithm is:", options:["A device","A step-by-step method","A virus","A folder"], ans:1 },
    { q:"Input device:", options:["Monitor","Printer","Keyboard","Speaker"], ans:2 },
    { q:"Output device:", options:["Mouse","Keyboard","Monitor","Scanner"], ans:2 },
    { q:"URL stands for:", options:["Uniform Resource Locator","Universal Record Link","Unique Resource List","Unified Route Link"], ans:0 },
    { q:"Wi-Fi is used for:", options:["Cooking","Wireless internet","Printing paper","Charging"], ans:1 },
    { q:"Data stored in tables:", options:["Browser","Database","Compiler","Cache only"], ans:1 },
    { q:"Example of a programming language:", options:["HTTP","Python","URL","WWW"], ans:1 },
    { q:"File extension of JavaScript:", options:[".html",".css",".js",".png"], ans:2 },
    { q:"Git is mainly for:", options:["Gaming","Version control","Video editing","Music"], ans:1 },
    { q:"A bug is:", options:["Feature","Error in code","Hardware upgrade","Database"], ans:1 },
    { q:"Debugging means:", options:["Adding errors","Fixing errors","Deleting files","Publishing"], ans:1 },
    { q:"A compiler converts:", options:["Binary to text","Code to machine language","Images to text","Wi-Fi to internet"], ans:1 },
    { q:"Internet is a:", options:["Single computer","Network of networks","A file","A browser"], ans:1 },
    { q:"HTTP is used for:", options:["Web communication","Gaming only","Photo storage","Keyboard control"], ans:0 },
    { q:"A function is:", options:["Reusable block of code","A keyboard","A virus","A folder"], ans:0 },
    { q:"An array stores:", options:["One value only","Multiple values","Only images","Only audio"], ans:1 },
    { q:"Cloud storage means:", options:["Storage on your table","Storage on internet servers","Storage only in RAM","Storage in CPU"], ans:1 },
    { q:"Two-factor authentication improves:", options:["Speed","Security","Color","Battery"], ans:1 },
    { q:"Strong password should have:", options:["Only numbers","Only letters","Mix of letters/numbers/symbols","Only your name"], ans:2 }
  ],

  "English Grammar": [
    { q:"Choose the correct article: ___ apple", options:["a","an","the","no article"], ans:1 },
    { q:"Past tense of 'go' is:", options:["goed","went","goes","going"], ans:1 },
    { q:"Plural of 'child' is:", options:["childs","childes","children","childrens"], ans:2 },
    { q:"He ___ to school every day.", options:["go","goes","going","gone"], ans:1 },
    { q:"I have ___ my homework.", options:["do","did","done","doing"], ans:2 },
    { q:"Opposite of 'hot' is:", options:["warm","cold","cool","fire"], ans:1 },
    { q:"A synonym of 'happy' is:", options:["sad","joyful","angry","weak"], ans:1 },
    { q:"Choose correct: She is ___ honest.", options:["a","an","the","—"], ans:3 },
    { q:"Correct preposition: good ___ maths", options:["in","at","on","for"], ans:1 },
    { q:"Correct: I am interested ___ music.", options:["on","in","at","to"], ans:1 },
    { q:"Choose correct sentence:", options:["He don't like tea.","He doesn't like tea.","He not likes tea.","He doesn't likes tea."], ans:1 },
    { q:"Question tag: You are coming, ___?", options:["isn't you","aren't you","don't you","won't you"], ans:1 },
    { q:"Comparative of 'tall' is:", options:["taller","tallest","more tall","tally"], ans:0 },
    { q:"Superlative of 'good' is:", options:["goodest","better","best","more good"], ans:2 },
    { q:"Correct: There ___ many students.", options:["is","are","was","be"], ans:1 },
    { q:"Choose correct: I ___ seen him.", options:["has","have","had","having"], ans:1 },
    { q:"He ___ playing now.", options:["is","are","am","be"], ans:0 },
    { q:"Choose correct: They ___ finished.", options:["has","have","is","was"], ans:1 },
    { q:"Pronoun for 'Ravi and I':", options:["We","Us","They","Them"], ans:0 },
    { q:"Choose correct: This is ___ book.", options:["me","my","mine","I"], ans:1 },
    { q:"Correct spelling:", options:["definately","definitely","definitly","definatly"], ans:1 },
    { q:"A noun is a:", options:["Action word","Naming word","Describing word","Joining word"], ans:1 },
    { q:"A verb is a:", options:["Naming word","Action word","Place word","Number word"], ans:1 },
    { q:"An adjective describes a:", options:["Noun","Verb","Preposition","Conjunction"], ans:0 },
    { q:"Correct: ___ you help me?", options:["Can","Could","Both A and B","None"], ans:2 },
    { q:"Choose correct: I ___ a pen.", options:["has","have","having","had"], ans:1 },
    { q:"Correct: She ___ a pen.", options:["have","has","having","had"], ans:1 },
    { q:"Choose correct: If it rains, we ___ stay home.", options:["will","would","did","was"], ans:0 },
    { q:"Correct: He is ___ than me.", options:["tall","taller","tallest","more taller"], ans:1 },
    { q:"Choose correct: I saw ___ elephant.", options:["a","an","the","—"], ans:1 }
  ],

  "General Knowledge (GK)": [
    { q:"Capital of India:", options:["Mumbai","New Delhi","Kolkata","Chennai"], ans:1 },
    { q:"Largest ocean:", options:["Indian","Pacific","Atlantic","Arctic"], ans:1 },
    { q:"Red Planet:", options:["Earth","Mars","Jupiter","Venus"], ans:1 },
    { q:"National animal of India:", options:["Lion","Tiger","Elephant","Leopard"], ans:1 },
    { q:"Currency of Japan:", options:["Yen","Won","Dollar","Ruble"], ans:0 },
    { q:"Largest continent:", options:["Africa","Asia","Europe","Australia"], ans:1 },
    { q:"Smallest continent:", options:["Europe","Australia","Africa","South America"], ans:1 },
    { q:"World’s longest river (common GK):", options:["Amazon","Nile","Ganga","Yangtze"], ans:1 },
    { q:"Taj Mahal is in:", options:["Delhi","Agra","Jaipur","Mumbai"], ans:1 },
    { q:"Father of Nation (India):", options:["Nehru","Gandhi","Patel","Bose"], ans:1 },
    { q:"Sun rises in the:", options:["North","South","East","West"], ans:2 },
    { q:"Largest planet:", options:["Earth","Mars","Jupiter","Venus"], ans:2 },
    { q:"Fastest land animal:", options:["Lion","Cheetah","Horse","Tiger"], ans:1 },
    { q:"Largest mammal:", options:["Elephant","Blue whale","Giraffe","Rhino"], ans:1 },
    { q:"National bird of India:", options:["Peacock","Eagle","Parrot","Crow"], ans:0 },
    { q:"First month of year:", options:["December","January","March","April"], ans:1 },
    { q:"7 days make a:", options:["Month","Week","Year","Decade"], ans:1 },
    { q:"1 decade =", options:["5 years","10 years","20 years","100 years"], ans:1 },
    { q:"Instrument to measure temperature:", options:["Barometer","Thermometer","Speedometer","Ammeter"], ans:1 },
    { q:"Earth is the ___ planet from Sun:", options:["2nd","3rd","4th","5th"], ans:1 },
    { q:"Largest desert:", options:["Sahara","Gobi","Thar","Kalahari"], ans:0 },
    { q:"India’s national sport (trick GK):", options:["Hockey","Cricket","Kabaddi","No official sport"], ans:3 },
    { q:"Number of letters in English alphabet:", options:["24","25","26","27"], ans:2 },
    { q:"Largest bone in human body:", options:["Skull","Femur","Rib","Humerus"], ans:1 },
    { q:"Water freezes at:", options:["0°C","10°C","50°C","100°C"], ans:0 },
    { q:"Earth’s natural satellite:", options:["Mars","Moon","Sun","Venus"], ans:1 },
    { q:"Gas we breathe most:", options:["Oxygen","Nitrogen","CO2","Hydrogen"], ans:1 },
    { q:"Plants make food by:", options:["Respiration","Photosynthesis","Digestion","Fermentation"], ans:1 },
    { q:"Primary color set (light):", options:["RGB","CMYK","RYB","HSL"], ans:0 },
    { q:"1 hour =", options:["30 min","60 min","90 min","100 min"], ans:1 }
  ],

  "History (India)": [
    { q:"First President of India:", options:["Dr. Rajendra Prasad","Nehru","Gandhi","Sardar Patel"], ans:0 },
    { q:"Indus Valley Civilization is also called:", options:["Harappan","Vedic","Gupta","Mauryan"], ans:0 },
    { q:"Ashoka belonged to:", options:["Gupta","Maurya","Chola","Mughal"], ans:1 },
    { q:"Taj Mahal was built by:", options:["Akbar","Shah Jahan","Aurangzeb","Babur"], ans:1 },
    { q:"Capital of Mughal empire (common):", options:["Delhi","Agra","Jaipur","Lahore"], ans:0 },
    { q:"Quit India Movement year:", options:["1919","1920","1942","1947"], ans:2 },
    { q:"India got independence in:", options:["1945","1946","1947","1950"], ans:2 },
    { q:"First Prime Minister of India:", options:["Nehru","Patel","Gandhi","Bose"], ans:0 },
    { q:"National flag has ____ colors (stripes):", options:["2","3","4","5"], ans:1 },
    { q:"Battle of Plassey year:", options:["1757","1857","1657","1957"], ans:0 },
    { q:"Father of Indian Constitution:", options:["B. R. Ambedkar","Nehru","Patel","Gandhi"], ans:0 },
    { q:"Capital of British India (later period):", options:["Mumbai","Delhi","Kolkata","Chennai"], ans:1 },
    { q:"Revolt of 1857 is also called:", options:["First War of Independence","Quit India","Non-Cooperation","Civil Disobedience"], ans:0 },
    { q:"Gandhi’s first major movement in India:", options:["Kheda","Champaran","Quit India","Swadeshi"], ans:1 },
    { q:"Jallianwala Bagh incident year:", options:["1919","1905","1942","1857"], ans:0 },
    { q:"Sardar Patel is known as:", options:["Iron Man of India","Netaji","Lokmanya","Deshbandhu"], ans:0 },
    { q:"Aryabhata is related to:", options:["Math/Astronomy","Painting","Music","Politics"], ans:0 },
    { q:"Gupta period is called:", options:["Golden Age","Dark Age","Modern Age","Stone Age"], ans:0 },
    { q:"Mahatma Gandhi was born in:", options:["Porbandar","Delhi","Agra","Pune"], ans:0 },
    { q:"Indian Republic Day:", options:["15 Aug","26 Jan","2 Oct","1 May"], ans:1 },
    { q:"Indian Constitution adopted on:", options:["26 Nov 1949","15 Aug 1947","26 Jan 1950","2 Oct 1948"], ans:0 },
    { q:"Ashoka embraced:", options:["Hinduism","Buddhism","Jainism","Islam"], ans:1 },
    { q:"Chola dynasty known for:", options:["Naval power","Desert wars","Ice trade","Space"], ans:0 },
    { q:"Mughal founder Babur came from:", options:["Central Asia","Europe","Africa","Australia"], ans:0 },
    { q:"Dandi March year:", options:["1920","1930","1942","1919"], ans:1 },
    { q:"Non-Cooperation Movement started in:", options:["1920","1930","1947","1857"], ans:0 },
    { q:"The Ashoka Chakra has ____ spokes.", options:["12","18","24","32"], ans:2 },
    { q:"The Red Fort is in:", options:["Agra","Delhi","Jaipur","Mumbai"], ans:1 },
    { q:"Indian National Congress founded in:", options:["1885","1905","1857","1947"], ans:0 }
  ],

  "Geography (World)": [
    { q:"Largest ocean:", options:["Indian","Pacific","Atlantic","Arctic"], ans:1 },
    { q:"Highest mountain:", options:["K2","Everest","Kilimanjaro","Elbrus"], ans:1 },
    { q:"Sahara is a:", options:["River","Desert","Mountain","Ocean"], ans:1 },
    { q:"Capital of Japan:", options:["Kyoto","Osaka","Tokyo","Seoul"], ans:2 },
    { q:"Nile is a:", options:["Mountain","River","Desert","Sea"], ans:1 },
    { q:"Equator divides Earth into:", options:["East/West","North/South","Up/Down","Hot/Cold"], ans:1 },
    { q:"Map directions: top usually is:", options:["South","North","East","West"], ans:1 },
    { q:"Largest continent:", options:["Africa","Asia","Europe","Australia"], ans:1 },
    { q:"Smallest continent:", options:["Europe","Australia","Africa","Asia"], ans:1 },
    { q:"India is in which continent?", options:["Africa","Asia","Europe","Australia"], ans:1 },
    { q:"Amazon is a:", options:["Desert","River","Mountain","Plateau"], ans:1 },
    { q:"Pacific Ocean is:", options:["Smallest","Largest","Shallowest","Frozen"], ans:1 },
    { q:"Greenland is:", options:["Country","Island","Ocean","Desert"], ans:1 },
    { q:"Himalayas are in:", options:["India/Nepal region","Africa","Europe","Australia"], ans:0 },
    { q:"The Tropic of Cancer is:", options:["0° latitude","23.5° N","23.5° S","66.5° N"], ans:1 },
    { q:"The Tropic of Capricorn is:", options:["0°","23.5° N","23.5° S","66.5° S"], ans:2 },
    { q:"Antarctica is:", options:["Hot desert","Frozen continent","Island","River"], ans:1 },
    { q:"Most populated country (recent years):", options:["India","USA","Russia","Japan"], ans:0 },
    { q:"Largest country by area:", options:["China","Canada","Russia","USA"], ans:2 },
    { q:"Mount Everest is in:", options:["India","Nepal/China region","Japan","USA"], ans:1 },
    { q:"A peninsula is land surrounded by water on:", options:["1 side","2 sides","3 sides","4 sides"], ans:2 },
    { q:"An island is surrounded by water on:", options:["2 sides","3 sides","All sides","No sides"], ans:2 },
    { q:"The Arctic Circle is at:", options:["23.5°","45°","66.5° N","90°"], ans:2 },
    { q:"Longitude lines run:", options:["East-West","North-South","Diagonal","Circular"], ans:1 },
    { q:"Latitude lines run:", options:["East-West","North-South","Vertical only","Random"], ans:0 },
    { q:"A plateau is:", options:["Flat high land","Deep valley","Ocean floor","River bank"], ans:0 },
    { q:"Delta forms at:", options:["River source","River mouth","Mountain top","Desert"], ans:1 },
    { q:"Ocean water is:", options:["Fresh","Salty","Sweet","Neutral"], ans:1 },
    { q:"A strait is:", options:["Wide land","Narrow water passage","Mountain gap","Forest"], ans:1 },
    { q:"A gulf is:", options:["Land area","Part of sea into land","River","Mountain"], ans:1 }
  ],

  "Economics (Basics)": [
    { q:"Money is mainly used as:", options:["A toy","Medium of exchange","Only decoration","Only tax"], ans:1 },
    { q:"Demand generally increases when price:", options:["Increases","Decreases","Stays same","Doubles"], ans:1 },
    { q:"Supply generally increases when price:", options:["Increases","Decreases","Stops","None"], ans:0 },
    { q:"Inflation means:", options:["Prices fall","Prices rise","No money","Free goods"], ans:1 },
    { q:"GDP stands for:", options:["Gross Domestic Product","General Daily Profit","Global Demand Price","Gross Dealer Payment"], ans:0 },
    { q:"A budget is:", options:["A plan of income & expenses","A type of coin","A bank account","A tax"], ans:0 },
    { q:"Savings is:", options:["Money spent","Money kept for future","Money burned","No money"], ans:1 },
    { q:"Investment means:", options:["Spending all","Putting money to grow","Throwing away","Only donating"], ans:1 },
    { q:"Bank’s main function:", options:["Cooking","Keeping money safe","Painting","Sports"], ans:1 },
    { q:"Interest is:", options:["Extra money paid/earned on loan/savings","A game","A tax only","A bill"], ans:0 },
    { q:"Tax is collected by:", options:["Schools","Government","Shops","Cars"], ans:1 },
    { q:"Exports are goods:", options:["Bought from other countries","Sold to other countries","Hidden","Destroyed"], ans:1 },
    { q:"Imports are goods:", options:["Sold to other countries","Bought from other countries","Burned","Free"], ans:1 },
    { q:"Profit =", options:["Cost - Revenue","Revenue - Cost","Revenue + Cost","Tax - Cost"], ans:1 },
    { q:"Loss occurs when:", options:["Revenue > Cost","Cost > Revenue","Cost = Revenue","No cost"], ans:1 },
    { q:"Need vs Want: Need is:", options:["Essential","Luxury","Optional","Random"], ans:0 },
    { q:"Scarcity means:", options:["Unlimited resources","Limited resources","Free goods","No demand"], ans:1 },
    { q:"Market is a place for:", options:["Sleeping","Buying and selling","Only studying","Only traveling"], ans:1 },
    { q:"Producer is:", options:["One who buys","One who sells/creates goods","Only studies","Only saves"], ans:1 },
    { q:"Consumer is:", options:["One who buys/uses goods","Only sells","Only taxes","Only invests"], ans:0 },
    { q:"Entrepreneur is:", options:["Risk-taker starting business","Only teacher","Only doctor","Only athlete"], ans:0 },
    { q:"Unemployment means:", options:["People working","People without jobs","No money exists","No schools"], ans:1 },
    { q:"Income is money:", options:["Earned","Lost","Burned","Thrown"], ans:0 },
    { q:"A loan is:", options:["Borrowed money","Free money","Tax","Gift only"], ans:0 },
    { q:"Demand curve usually slopes:", options:["Upward","Downward","Flat","Vertical"], ans:1 },
    { q:"Supply curve usually slopes:", options:["Downward","Upward","Flat","None"], ans:1 },
    { q:"Microeconomics studies:", options:["Whole economy","Individual markets","Only planets","Only history"], ans:1 },
    { q:"Macroeconomics studies:", options:["Individual choice","Whole economy","Only math","Only biology"], ans:1 },
    { q:"Currency of India:", options:["Dollar","Rupee","Yen","Euro"], ans:1 },
    { q:"A recession is:", options:["Economic slowdown","Economic boom","Free market","No taxes"], ans:0 }
  ],

  "Current Affairs (Basics)": [
    { q:"A democracy means:", options:["Rule by one","Rule by people","Rule by army","Rule by kings"], ans:1 },
    { q:"Elections are used to:", options:["Select leaders","Stop schools","Create rain","Make robots"], ans:0 },
    { q:"Constitution is:", options:["A rule book for country","A movie","A phone","A car"], ans:0 },
    { q:"Supreme Court is part of:", options:["Judiciary","Legislature","Executive","Sports"], ans:0 },
    { q:"Parliament is part of:", options:["Judiciary","Legislature","Executive","Police"], ans:1 },
    { q:"Media is often called:", options:["Fourth pillar","Second sun","Third ocean","Fifth mountain"], ans:0 },
    { q:"Vaccines help by:", options:["Causing disease","Preventing disease","Stopping oxygen","Breaking bones"], ans:1 },
    { q:"Internet safety includes:", options:["Sharing passwords","Strong passwords","Clicking random links","No updates"], ans:1 },
    { q:"Renewable energy example:", options:["Coal","Petrol","Solar","Diesel"], ans:2 },
    { q:"Climate change relates to:", options:["Weather patterns long-term","Only night time","Only oceans","Only cars"], ans:0 },
    { q:"A pandemic is:", options:["Local festival","Global disease outbreak","New phone","New coin"], ans:1 },
    { q:"Digital payment example:", options:["UPI","Stone","Leaf","Sand"], ans:0 },
    { q:"Cyberbullying happens:", options:["Online","Only in forests","Only in oceans","Only in books"], ans:0 },
    { q:"A satellite is used for:", options:["Communication/Navigation","Cooking","Painting","Digging"], ans:0 },
    { q:"GPS helps in:", options:["Finding location","Making tea","Growing hair","Changing color"], ans:0 },
    { q:"AI stands for:", options:["Auto Internet","Artificial Intelligence","Advanced Image","Active Idea"], ans:1 },
    { q:"Robots are:", options:["Human teachers","Machines that can perform tasks","Trees","Cars only"], ans:1 },
    { q:"Data privacy means:", options:["Sharing all data","Protecting personal data","Deleting internet","No phones"], ans:1 },
    { q:"Fake news is:", options:["True news","False/misleading info","Only cartoons","Only math"], ans:1 },
    { q:"Recycling helps:", options:["Increase waste","Reduce waste","Stop oxygen","Increase pollution"], ans:1 },
    { q:"Electric vehicles use:", options:["Petrol only","Diesel only","Battery power","Coal"], ans:2 },
    { q:"Space missions explore:", options:["Only oceans","Outer space","Only forests","Only deserts"], ans:1 },
    { q:"A startup is:", options:["New business","Old building","New road","Old law"], ans:0 },
    { q:"Entrepreneurship means:", options:["Building solutions/business","Only homework","Only games","Only sleeping"], ans:0 },
    { q:"Public health focuses on:", options:["Community health","Only sports","Only phones","Only trains"], ans:0 },
    { q:"Traffic rules help:", options:["Increase accidents","Reduce accidents","No effect","Stop cars"], ans:1 },
    { q:"A law is made by:", options:["Legislature","Judiciary","Ocean","Mountains"], ans:0 },
    { q:"Human rights are:", options:["Basic rights for all","Only for robots","Only for rich","Only for students"], ans:0 },
    { q:"A budget is announced by:", options:["Government","Only shops","Only schools","Only phones"], ans:0 },
    { q:"National anthem is:", options:["A song of nation","A math formula","A car model","A bank"], ans:0 }
  ],

  "Travel & Places": [
    { q:"City of Canals:", options:["Paris","Venice","Rome","London"], ans:1 },
    { q:"Capital of France:", options:["Rome","Paris","Berlin","Madrid"], ans:1 },
    { q:"Capital of UK:", options:["Manchester","London","Birmingham","Glasgow"], ans:1 },
    { q:"Capital of USA:", options:["New York","Washington, D.C.","Los Angeles","Chicago"], ans:1 },
    { q:"Capital of UAE:", options:["Dubai","Abu Dhabi","Sharjah","Doha"], ans:1 },
    { q:"Taj Mahal is in:", options:["Delhi","Agra","Jaipur","Mumbai"], ans:1 },
    { q:"Eiffel Tower is in:", options:["London","Paris","Rome","Berlin"], ans:1 },
    { q:"Great Wall is in:", options:["India","China","Japan","Korea"], ans:1 },
    { q:"Pyramids are in:", options:["Greece","Egypt","Italy","Mexico"], ans:1 },
    { q:"Colosseum is in:", options:["Rome","Paris","Madrid","Athens"], ans:0 },
    { q:"Mount Fuji is in:", options:["China","Japan","India","USA"], ans:1 },
    { q:"Statue of Liberty is in:", options:["USA","UK","France","Canada"], ans:0 },
    { q:"Big Ben is in:", options:["Paris","London","Rome","Berlin"], ans:1 },
    { q:"Sydney Opera House is in:", options:["Australia","USA","UK","India"], ans:0 },
    { q:"Niagara Falls is on border of:", options:["India-Nepal","USA-Canada","France-Germany","China-Russia"], ans:1 },
    { q:"Himalayas are mainly in:", options:["Europe","Asia","Africa","Australia"], ans:1 },
    { q:"Kerala is in:", options:["North India","South India","East India","West India"], ans:1 },
    { q:"Kochi is in:", options:["Kerala","Tamil Nadu","Karnataka","Goa"], ans:0 },
    { q:"Goa is famous for:", options:["Deserts","Beaches","Glaciers","Volcanoes"], ans:1 },
    { q:"Thar Desert is in:", options:["Rajasthan","Kerala","Assam","Kashmir"], ans:0 },
    { q:"Capital of Kerala:", options:["Kochi","Thiruvananthapuram","Kozhikode","Kannur"], ans:1 },
    { q:"Capital of Tamil Nadu:", options:["Chennai","Madurai","Coimbatore","Salem"], ans:0 },
    { q:"Capital of Karnataka:", options:["Mysuru","Bengaluru","Mangaluru","Hubli"], ans:1 },
    { q:"Capital of Andhra Pradesh (common):", options:["Hyderabad","Amaravati","Vijayawada","Visakhapatnam"], ans:1 },
    { q:"Mecca is in:", options:["India","Saudi Arabia","UAE","Qatar"], ans:1 },
    { q:"Mount Everest region is:", options:["Nepal/China","USA/Canada","France/Spain","Brazil/Argentina"], ans:0 },
    { q:"Amazon rainforest is in:", options:["Asia","South America","Europe","Australia"], ans:1 },
    { q:"Sahara is in:", options:["Africa","Asia","Europe","Australia"], ans:0 },
    { q:"Ganga river mainly flows in:", options:["India","USA","UK","Japan"], ans:0 },
    { q:"Indian Ocean lies to the:", options:["South of India","North of India","West of India","East of India"], ans:0 }
  ],

  "Sports (Mixed)": [
    { q:"Football is played with:", options:["Bat","Ball","Racket","Stick"], ans:1 },
    { q:"Cricket has ____ players per team:", options:["9","10","11","12"], ans:2 },
    { q:"A hat-trick means:", options:["3 goals/wickets by one player","10 goals","1 goal","No goal"], ans:0 },
    { q:"Olympics are held every:", options:["2 years","3 years","4 years","5 years"], ans:2 },
    { q:"Tennis uses:", options:["Racket","Bat","Stick","Gloves"], ans:0 },
    { q:"Badminton uses:", options:["Ball","Shuttlecock","Puck","Stone"], ans:1 },
    { q:"Hockey is played with:", options:["Stick","Racket","Bat","Net"], ans:0 },
    { q:"Basketball hoop is called:", options:["Goalpost","Ring","Net only","Wicket"], ans:1 },
    { q:"Cricket world cup is organized by:", options:["FIFA","ICC","IOC","BCCI"], ans:1 },
    { q:"Football world cup is organized by:", options:["FIFA","ICC","IOC","UEFA"], ans:0 },
    { q:"Swimming is done in:", options:["Ground","Pool","Court","Ring"], ans:1 },
    { q:"Boxing is a:", options:["Team sport","Combat sport","Water sport","Board game"], ans:1 },
    { q:"Kabaddi is:", options:["Indian sport","Only USA sport","Only UK sport","Water sport"], ans:0 },
    { q:"Marathon distance is:", options:["10 km","21.1 km","42.195 km","100 km"], ans:2 },
    { q:"In chess, a 'checkmate' means:", options:["Game ends","Piece lost","Draw","Restart"], ans:0 },
    { q:"In cricket, LBW stands for:", options:["Leg Before Wicket","Long Ball Wide","Left Bat Win","Leg Bat Wicket"], ans:0 },
    { q:"In football, goalkeeper can use hands:", options:["Anywhere","Only in penalty box","Never","Only outside field"], ans:1 },
    { q:"In badminton, game starts with:", options:["Serve","Goal","Kick","Throw"], ans:0 },
    { q:"A sprinter runs:", options:["Short distance fast","Long distance slow","Only swimming","Only cycling"], ans:0 },
    { q:"Cycling uses:", options:["Car","Bicycle","Boat","Plane"], ans:1 },
    { q:"Wicket is used in:", options:["Football","Cricket","Tennis","Hockey"], ans:1 },
    { q:"A referee is:", options:["Player","Official","Coach","Fan"], ans:1 },
    { q:"A draw means:", options:["One team wins","Both equal","No match","Only rain"], ans:1 },
    { q:"Penalty is in:", options:["Cricket","Football","Chess","Swimming"], ans:1 },
    { q:"Offside is a rule in:", options:["Football","Cricket","Tennis","Badminton"], ans:0 },
    { q:"Grand Slam relates to:", options:["Tennis majors","Cricket league","Football cup","Kabaddi"], ans:0 },
    { q:"Chess pieces include:", options:["King","Wicket","Bat","Goal"], ans:0 },
    { q:"A team captain leads:", options:["Only fans","The team","The stadium","The ball"], ans:1 },
    { q:"Stadium is used for:", options:["Sports events","Cooking","Studying only","Shopping"], ans:0 },
    { q:"Warm-up helps to:", options:["Prevent injury","Increase laziness","Stop breathing","Nothing"], ans:0 }
  ],

  "Movies & Media": [
    { q:"A film director mainly controls:", options:["Story vision","Camera lens only","Ticket price","Food"], ans:0 },
    { q:"Animation means:", options:["Live acting","Moving drawings/graphics","Audio only","Sports"], ans:1 },
    { q:"A script is:", options:["Poster","Written story/dialogue","Camera","Speaker"], ans:1 },
    { q:"A sequel is:", options:["First film","Second part of film","Trailer","Song"], ans:1 },
    { q:"A trailer is:", options:["Full movie","Short preview","Ticket","Camera"], ans:1 },
    { q:"A soundtrack is:", options:["Movie music","Movie poster","Movie hall","Movie script"], ans:0 },
    { q:"An actor performs:", options:["Roles","Editing only","Lighting only","Ticketing"], ans:0 },
    { q:"Cinematography is:", options:["Camera work","Cooking","Dance only","Painting"], ans:0 },
    { q:"Editing means:", options:["Cutting and arranging scenes","Acting","Singing","Drawing"], ans:0 },
    { q:"A genre is:", options:["Type/category of film","Ticket price","Camera lens","Food"], ans:0 },
    { q:"Comedy is meant to:", options:["Make people laugh","Make people cry","Teach math","Stop music"], ans:0 },
    { q:"Horror aims to:", options:["Scare","Teach grammar","Stop sound","Increase sleep"], ans:0 },
    { q:"Documentary is:", options:["Fiction story","Real-life based film","Cartoon only","Sports only"], ans:1 },
    { q:"OTT examples:", options:["Netflix","Notebook","Keyboard","Oven"], ans:0 },
    { q:"A subtitle shows:", options:["Extra images","Text of dialogue","Only sound","Only music"], ans:1 },
    { q:"A dubbing means:", options:["Adding background","Replacing voice in another language","Removing scenes","Adding tickets"], ans:1 },
    { q:"A producer mainly:", options:["Manages budget/production","Does only acting","Only dances","Only writes code"], ans:0 },
    { q:"A screenplay includes:", options:["Scene + dialogue details","Only music","Only posters","Only tickets"], ans:0 },
    { q:"A casting is:", options:["Choosing actors","Choosing camera","Choosing food","Choosing bus"], ans:0 },
    { q:"VFX stands for:", options:["Visual Effects","Voice FX","Video Fix","Value X Factor"], ans:0 },
    { q:"SFX stands for:", options:["Sound Effects","Super FX","Scene Fix","Story FX"], ans:0 },
    { q:"A cinematic universe is:", options:["One film only","Connected stories across films","Only cartoons","Only music"], ans:1 },
    { q:"A villain is:", options:["Hero","Bad character","Director","Producer"], ans:1 },
    { q:"A protagonist is:", options:["Main character","Background actor","Camera","Subtitle"], ans:0 },
    { q:"IMAX is related to:", options:["Large-screen format","Music only","Food","Costume"], ans:0 },
    { q:"A scene is:", options:["Part of movie","Ticket","Song only","Camera only"], ans:0 },
    { q:"A dialogue is:", options:["Conversation in film","Only background","Only subtitle","Only music"], ans:0 },
    { q:"A cameo is:", options:["Short appearance by known person","Big fight","Long speech","Movie ending"], ans:0 },
    { q:"A rating shows:", options:["Age suitability","Camera model","Food quality","Battery"], ans:0 },
    { q:"A premiere is:", options:["First public show","Last show","Random show","No show"], ans:0 }
  ],

  "Logical Reasoning": [
    { q:"If all A are B and all B are C, then all A are:", options:["A","B","C","None"], ans:2 },
    { q:"Odd one out: 2, 4, 6, 9", options:["2","4","6","9"], ans:3 },
    { q:"Find next: 1, 3, 5, 7, ___", options:["8","9","10","11"], ans:1 },
    { q:"A is taller than B. B taller than C. Tallest is:", options:["A","B","C","Cannot say"], ans:0 },
    { q:"Mirror of LEFT is:", options:["TFEL","LEFT","L E F T","None"], ans:0 },
    { q:"If today is Monday, after 3 days it is:", options:["Tuesday","Wednesday","Thursday","Friday"], ans:2 },
    { q:"If 5+5=10 then 5×5=", options:["20","25","30","10"], ans:1 },
    { q:"Find next: 2, 4, 8, 16, ___", options:["18","20","24","32"], ans:3 },
    { q:"Which number is smallest?", options:["-1","0","1","2"], ans:0 },
    { q:"If CAT=3 letters, then DOG has:", options:["2","3","4","5"], ans:1 },
    { q:"If 1=Sunday, 2=Monday, then 7=", options:["Friday","Saturday","Sunday","Thursday"], ans:1 },
    { q:"Complete: A, C, E, G, ___", options:["H","I","J","K"], ans:1 },
    { q:"If 10 is even, 11 is:", options:["Even","Odd","Prime only","None"], ans:1 },
    { q:"Opposite of North is:", options:["East","West","South","Up"], ans:2 },
    { q:"If 3 pencils cost 15, 1 pencil costs:", options:["3","4","5","6"], ans:2 },
    { q:"Find next: 10, 20, 30, 40, ___", options:["45","50","55","60"], ans:1 },
    { q:"If all roses are flowers, then rose is:", options:["Flower","Tree","Animal","Metal"], ans:0 },
    { q:"Odd one: Apple, Banana, Carrot, Mango", options:["Apple","Banana","Carrot","Mango"], ans:2 },
    { q:"If 2+3=5, then 2+5=", options:["5","6","7","8"], ans:2 },
    { q:"Find next: 9, 7, 5, 3, ___", options:["2","1","0","-1"], ans:1 },
    { q:"A square has ____ sides.", options:["3","4","5","6"], ans:1 },
    { q:"Which is NOT a shape?", options:["Circle","Triangle","Apple","Square"], ans:2 },
    { q:"If you rearrange 'STOP' you get:", options:["POTS","TOPS","Both A and B","None"], ans:2 },
    { q:"If 12 is divisible by 3, then 15 is divisible by:", options:["2","3","4","5"], ans:1 },
    { q:"Next: 5, 10, 15, 20, ___", options:["22","24","25","30"], ans:2 },
    { q:"If x=2, then x+x+x =", options:["4","6","8","10"], ans:1 },
    { q:"Which is a prime number?", options:["21","27","29","35"], ans:2 },
    { q:"If 100 ÷ 10 =", options:["1","5","10","20"], ans:2 },
    { q:"Next: 1, 4, 9, 16, ___", options:["20","24","25","30"], ans:2 },
    { q:"If it is raining, you use:", options:["Sunglasses","Umbrella","Helmet","Shoes"], ans:1 }
  ],

  "Health & Nutrition": [
    { q:"A balanced diet includes:", options:["Only carbs","Only protein","All nutrients","Only fats"], ans:2 },
    { q:"Vitamin C source:", options:["Orange","Rice","Oil","Salt"], ans:0 },
    { q:"Protein helps in:", options:["Muscle repair","Only sleeping","Only reading","Only writing"], ans:0 },
    { q:"Water is important for:", options:["Hydration","Only height","Only hair","Only games"], ans:0 },
    { q:"Too much sugar can:", options:["Improve teeth","Cause tooth decay","Increase oxygen","Stop sleep"], ans:1 },
    { q:"Exercise helps:", options:["Health","Only boredom","Only anger","Nothing"], ans:0 },
    { q:"BMI relates to:", options:["Height+Weight","Only age","Only gender","Only food"], ans:0 },
    { q:"Junk food often has:", options:["High nutrients","High sugar/salt/fat","No calories","Only protein"], ans:1 },
    { q:"Sleep is important for:", options:["Growth and recovery","Only gaming","Only movies","Only travel"], ans:0 },
    { q:"Iron deficiency causes:", options:["Strong bones","Anemia","Super speed","No effect"], ans:1 },
    { q:"Calcium supports:", options:["Bones/teeth","Hair only","Eyes only","Ears only"], ans:0 },
    { q:"Fruits and vegetables provide:", options:["Vitamins/minerals","Only fat","Only salt","Only alcohol"], ans:0 },
    { q:"Handwashing reduces:", options:["Infections","Height","Weight","Study"], ans:0 },
    { q:"Dehydration means:", options:["Too much water","Not enough water","Too much protein","Too much sleep"], ans:1 },
    { q:"Sugary drinks can:", options:["Help teeth","Increase cavity risk","Make bones strong","Stop hunger forever"], ans:1 },
    { q:"A healthy habit:", options:["Smoking","Balanced meals","No sleep","Only junk"], ans:1 },
    { q:"Fiber helps in:", options:["Digestion","Vision","Hearing","Typing"], ans:0 },
    { q:"Fast food is usually:", options:["High in fat/salt","High in fiber","High in vitamins","No calories"], ans:0 },
    { q:"Good fat example:", options:["Olive oil","Plastic","Sand","Paper"], ans:0 },
    { q:"Salt should be:", options:["Very high","Moderate","Never","Only for kids"], ans:1 },
    { q:"A calorie is unit of:", options:["Energy","Length","Time","Speed"], ans:0 },
    { q:"Overeating leads to:", options:["Always strength","Weight gain","Instant height","No change"], ans:1 },
    { q:"Sunlight helps vitamin:", options:["A","B","C","D"], ans:3 },
    { q:"Healthy breakfast example:", options:["Fruits + eggs","Only chips","Only soda","Only candy"], ans:0 },
    { q:"Hydration best drink:", options:["Water","Soda","Energy drink","Oil"], ans:0 },
    { q:"Regular exercise improves:", options:["Heart health","Only anger","Only hunger","Only sleepiness"], ans:0 },
    { q:"Too much screen time can:", options:["Improve eyes","Cause eye strain","Fix posture","Increase height instantly"], ans:1 },
    { q:"Good posture helps:", options:["Back health","Only hair","Only voice","Only memory"], ans:0 },
    { q:"A healthy plate includes:", options:["Only rice","Some protein + veg + carbs","Only meat","Only sugar"], ans:1 },
    { q:"A doctor checks health issues when:", options:["Symptoms persist","Always ignore","Only at night","Never"], ans:0 }
  ],

  "Environment": [
    { q:"Planting trees helps:", options:["Reduce oxygen","Increase pollution","Improve air quality","Stop rain"], ans:2 },
    { q:"Recycling reduces:", options:["Waste","Water","Sunlight","Gravity"], ans:0 },
    { q:"Greenhouse gases include:", options:["CO2","Gold","Iron","Salt"], ans:0 },
    { q:"Global warming is:", options:["Cooling Earth","Rising average temperature","Only rainfall","Only wind"], ans:1 },
    { q:"Renewable energy example:", options:["Coal","Petrol","Solar","Diesel"], ans:2 },
    { q:"Plastic pollution harms:", options:["Animals/oceans","Only cars","Only books","Only clouds"], ans:0 },
    { q:"Water pollution means:", options:["Clean water","Dirty water","No water","Only ice"], ans:1 },
    { q:"Air pollution is caused by:", options:["Vehicles/industries","Trees","Rain","Books"], ans:0 },
    { q:"Saving electricity helps:", options:["Environment","Only phone battery","Only gaming","Nothing"], ans:0 },
    { q:"Deforestation means:", options:["Planting trees","Cutting forests","Cleaning water","Building roads only"], ans:1 },
    { q:"Ozone layer protects from:", options:["UV rays","Rain","Wind","Noise"], ans:0 },
    { q:"Littering is:", options:["Good","Bad","Necessary","Neutral"], ans:1 },
    { q:"Composting turns waste into:", options:["Fertilizer","Plastic","Metal","Glass"], ans:0 },
    { q:"Biodiversity means:", options:["Variety of life","Only humans","Only plants","Only animals"], ans:0 },
    { q:"Conserving water means:", options:["Wasting water","Using wisely","No water at all","Only drinking soda"], ans:1 },
    { q:"Noise pollution can affect:", options:["Hearing","Hair","Teeth","Nails"], ans:0 },
    { q:"A greenhouse effect is:", options:["Heat trapping","Cold trapping","Light blocking","Water freezing"], ans:0 },
    { q:"Clean energy includes:", options:["Wind","Coal","Petrol","Diesel"], ans:0 },
    { q:"Reduce, Reuse, Recycle are:", options:["3R’s","3C’s","3D’s","3P’s"], ans:0 },
    { q:"Using public transport can:", options:["Reduce pollution","Increase pollution","Stop roads","Stop rain"], ans:0 },
    { q:"A wildlife sanctuary protects:", options:["Animals","Cars","Phones","Buildings"], ans:0 },
    { q:"Soil erosion is:", options:["Loss of topsoil","Growth of soil","Making soil","Painting soil"], ans:0 },
    { q:"Climate is:", options:["Long-term weather pattern","Daily rain only","Only hot days","Only cold days"], ans:0 },
    { q:"Weather is:", options:["Short-term conditions","Long-term pattern","Always same","Only wind"], ans:0 },
    { q:"Marine life lives in:", options:["Desert","Ocean","Mountains","Sky"], ans:1 },
    { q:"Overfishing can:", options:["Reduce fish population","Increase fish forever","Stop oceans","Create deserts"], ans:0 },
    { q:"Reforestation means:", options:["Cutting trees","Planting trees again","Burning forests","Building factories"], ans:1 },
    { q:"Pollution control helps:", options:["Health","Only games","Only phones","Nothing"], ans:0 },
    { q:"A biodegradable waste is:", options:["Food waste","Plastic","Glass","Metal"], ans:0 },
    { q:"Using cloth bags reduces:", options:["Plastic use","Water use","Sunlight","Air"], ans:0 }
  ],

  "Entrepreneurship (Basics)": [
    { q:"A startup is:", options:["New business","Old building","New road","Old law"], ans:0 },
    { q:"Entrepreneur is:", options:["Risk-taker","Only employee","Only student","Only singer"], ans:0 },
    { q:"Revenue means:", options:["Money earned","Money lost","Only tax","Only debt"], ans:0 },
    { q:"Profit =", options:["Revenue - Cost","Cost - Revenue","Revenue + Cost","Tax - Cost"], ans:0 },
    { q:"Customer is:", options:["Person who buys","Only seller","Only investor","Only teacher"], ans:0 },
    { q:"Marketing helps to:", options:["Reach customers","Stop sales","Reduce products","Delete business"], ans:0 },
    { q:"Brand means:", options:["Identity of product/company","A fruit","A math symbol","A password"], ans:0 },
    { q:"A pitch is:", options:["Presentation to explain idea","A bat","A ball","A keyboard"], ans:0 },
    { q:"MVP stands for:", options:["Minimum Viable Product","Most Valuable Person","Maximum Value Plan","Main Video Program"], ans:0 },
    { q:"A competitor is:", options:["Rival business","Friend","Teacher","Customer"], ans:0 },
    { q:"Scaling means:", options:["Growing the business","Closing business","Sleeping","Only studying"], ans:0 },
    { q:"Investor provides:", options:["Money/resources","Only homework","Only music","Only paint"], ans:0 },
    { q:"Bootstrapping means:", options:["Self-funding","Only loans","Only donations","No money ever"], ans:0 },
    { q:"A business model explains:", options:["How it makes money","How to cook","How to sleep","How to travel"], ans:0 },
    { q:"Pricing is:", options:["Setting product cost","Deleting product","Free only","Random"], ans:0 },
    { q:"Feedback is:", options:["User opinions","Only hate","Only money","Only ads"], ans:0 },
    { q:"Iteration means:", options:["Improve repeatedly","Never change","Stop work","Delete app"], ans:0 },
    { q:"Value proposition means:", options:["What benefit you offer","Your phone model","Your password","Your haircut"], ans:0 },
    { q:"Target audience means:", options:["People you want to serve","Only enemies","Only teachers","Only relatives"], ans:0 },
    { q:"Customer retention means:", options:["Keeping users","Removing users","Blocking users","Ignoring users"], ans:0 },
    { q:"Churn means:", options:["Users leaving","Users joining","Profit","Tax"], ans:0 },
    { q:"Conversion means:", options:["Visitor becomes user/customer","User deletes app","No change","Only ads"], ans:0 },
    { q:"A roadmap is:", options:["Plan of features/time","A car map only","A phone case","A password list"], ans:0 },
    { q:"A founder is:", options:["Person who starts company","Person who buys","Person who edits","Person who watches"], ans:0 },
    { q:"A co-founder is:", options:["Partner founder","Customer","Teacher","Competitor"], ans:0 },
    { q:"Legal compliance means:", options:["Following laws","Breaking laws","Ignoring laws","Only paying cash"], ans:0 },
    { q:"User experience (UX) is:", options:["How easy/pleasant app feels","Only color","Only logo","Only code speed"], ans:0 },
    { q:"Customer support means:", options:["Helping users","Blocking users","Ignoring users","Only ads"], ans:0 },
    { q:"A subscription is:", options:["Recurring payment plan","One-time free","Only cash","No payment"], ans:0 },
    { q:"Growth comes from:", options:["Product + marketing + retention","Only luck","Only spending","Only sleep"], ans:0 }
  ],

  "Math (Percentages)": [
    { q:"50% of 200 =", options:["50","100","150","200"], ans:1 },
    { q:"10% of 300 =", options:["3","30","300","33"], ans:1 },
    { q:"25% of 80 =", options:["10","15","20","25"], ans:2 },
    { q:"1% of 500 =", options:["5","50","1","10"], ans:0 },
    { q:"20% of 150 =", options:["20","25","30","35"], ans:2 },
    { q:"75% as fraction is:", options:["3/4","1/3","2/5","4/3"], ans:0 },
    { q:"0.5 as percentage:", options:["5%","50%","500%","0.5%"], ans:1 },
    { q:"200 increased by 10% =", options:["210","220","230","240"], ans:1 },
    { q:"100 decreased by 20% =", options:["70","80","90","60"], ans:1 },
    { q:"If price 100 to 120, increase is:", options:["10%","15%","20%","25%"], ans:2 },
    { q:"If 40 is 20% of x, x =", options:["80","100","200","400"], ans:2 },
    { q:"If 30% of x is 60, x =", options:["120","180","200","240"], ans:1 },
    { q:"15% of 200 =", options:["20","25","30","35"], ans:2 },
    { q:"5% of 600 =", options:["20","25","30","35"], ans:2 },
    { q:"60% of 90 =", options:["45","50","54","60"], ans:2 },
    { q:"12.5% equals:", options:["1/8","1/4","1/2","1/16"], ans:0 },
    { q:"30% of 300 =", options:["30","60","90","120"], ans:2 },
    { q:"80% of 50 =", options:["20","30","40","45"], ans:2 },
    { q:"If 200 reduced to 150, decrease:", options:["10%","20%","25%","30%"], ans:2 },
    { q:"If 50 is 10% of x, x =", options:["100","200","300","500"], ans:3 },
    { q:"40% of 250 =", options:["50","75","100","125"], ans:2 },
    { q:"2% of 1000 =", options:["2","20","200","100"], ans:1 },
    { q:"95% of 200 =", options:["180","190","195","200"], ans:1 },
    { q:"If 20 is 5% of x, x =", options:["200","300","400","500"], ans:2 },
    { q:"Increase 50 by 50% =", options:["60","70","75","100"], ans:2 },
    { q:"Decrease 80 by 25% =", options:["40","50","60","70"], ans:2 },
    { q:"33.33% approx equals:", options:["1/3","1/2","2/3","1/4"], ans:0 },
    { q:"66.66% approx equals:", options:["1/3","1/2","2/3","3/4"], ans:2 },
    { q:"7% of 100 =", options:["5","6","7","8"], ans:2 },
    { q:"12% of 250 =", options:["20","25","30","35"], ans:2 }
  ],

  "Science (Space)": [
    { q:"The Sun is a:", options:["Planet","Star","Comet","Asteroid"], ans:1 },
    { q:"Earth is the ___ planet from Sun:", options:["2nd","3rd","4th","5th"], ans:1 },
    { q:"Moon is Earth’s:", options:["Star","Satellite","Planet","Asteroid"], ans:1 },
    { q:"Largest planet:", options:["Earth","Mars","Jupiter","Venus"], ans:2 },
    { q:"Red planet:", options:["Mars","Venus","Jupiter","Saturn"], ans:0 },
    { q:"A galaxy is:", options:["Group of stars","A planet","A comet","A cloud"], ans:0 },
    { q:"Milky Way is a:", options:["Galaxy","Planet","Star","Moon"], ans:0 },
    { q:"A comet has:", options:["Tail","Wheels","Fins","Roots"], ans:0 },
    { q:"Asteroids are found mostly in:", options:["Ocean","Asteroid belt","Earth","Moon"], ans:1 },
    { q:"The closest star to Earth is:", options:["Alpha Centauri","Sirius","Sun","Polaris"], ans:2 },
    { q:"Day and night happen due to:", options:["Revolution","Rotation","Eclipse","Seasons"], ans:1 },
    { q:"Seasons happen due to:", options:["Earth tilt + revolution","Rotation only","Moon","Clouds"], ans:0 },
    { q:"A light year measures:", options:["Time","Distance","Speed","Mass"], ans:1 },
    { q:"The Sun’s energy comes from:", options:["Fusion","Fission","Burning wood","Electricity"], ans:0 },
    { q:"First man on Moon:", options:["Neil Armstrong","Einstein","Newton","Galileo"], ans:0 },
    { q:"A telescope is used to:", options:["See far objects","Cook","Dig","Paint"], ans:0 },
    { q:"Satellites are used for:", options:["Communication","Cooking","Farming only","Swimming"], ans:0 },
    { q:"Gravity pulls objects:", options:["Up","Down toward mass","Sideways","No pull"], ans:1 },
    { q:"Black hole has:", options:["Strong gravity","No gravity","Only light","Only water"], ans:0 },
    { q:"Mercury is closest to:", options:["Moon","Sun","Earth","Mars"], ans:1 },
    { q:"Earth’s shape is:", options:["Flat","Sphere-like","Square","Triangle"], ans:1 },
    { q:"Venus is known as:", options:["Morning/Evening star","Red planet","Blue planet","Ring planet"], ans:0 },
    { q:"Saturn is famous for:", options:["Rings","Oceans","Mountains","Forests"], ans:0 },
    { q:"Uranus is:", options:["Gas giant","Rock only","Star","Comet"], ans:0 },
    { q:"Neptune appears:", options:["Blue","Red","Green","Yellow"], ans:0 },
    { q:"Eclipse happens when:", options:["Shadows align","Wind blows","Rain falls","Clouds vanish"], ans:0 },
    { q:"Solar eclipse involves:", options:["Sun, Moon, Earth","Earth, Mars","Moon, Jupiter","Sun only"], ans:0 },
    { q:"Lunar eclipse involves:", options:["Earth shadow on Moon","Moon shadow on Earth","Sun disappears","Stars fall"], ans:0 },
    { q:"A rocket needs:", options:["Thrust","Water","Wood","Paper"], ans:0 }
  ],

  "Math (Speed-Time-Distance)": [
    { q:"Speed = ?", options:["Distance ÷ Time","Time ÷ Distance","Distance × Time","Time + Distance"], ans:0 },
    { q:"Distance = ?", options:["Speed ÷ Time","Speed × Time","Time ÷ Speed","Speed + Time"], ans:1 },
    { q:"Time = ?", options:["Distance ÷ Speed","Speed ÷ Distance","Distance × Speed","Speed + Distance"], ans:0 },
    { q:"If speed=10 m/s, time=5 s, distance=", options:["2","15","50","100"], ans:2 },
    { q:"If distance=100 km, time=2 h, speed=", options:["20","40","50","60"], ans:2 },
    { q:"If speed=60 km/h, time=3 h, distance=", options:["120","150","180","200"], ans:2 },
    { q:"If distance=30 km, speed=10 km/h, time=", options:["1 h","2 h","3 h","4 h"], ans:2 },
    { q:"Average speed is:", options:["Total distance ÷ total time","Distance × time","Time ÷ distance","None"], ans:0 },
    { q:"If time is zero, speed is:", options:["0","Undefined","Always 1","Always 10"], ans:1 },
    { q:"If speed doubles, time for same distance:", options:["Doubles","Halves","Same","Zero"], ans:1 },
    { q:"15 m/s equals km/h:", options:["36","45","54","60"], ans:2 },
    { q:"5 m/s equals km/h:", options:["9","12","18","20"], ans:2 },
    { q:"If you travel 10 km in 30 min, speed=", options:["10 km/h","20 km/h","30 km/h","40 km/h"], ans:1 },
    { q:"If you travel 120 km in 3 h, speed=", options:["30","40","50","60"], ans:1 },
    { q:"Uniform motion means:", options:["Constant speed","Changing speed","No motion","Random"], ans:0 },
    { q:"A speedometer measures:", options:["Speed","Distance","Time","Mass"], ans:0 },
    { q:"Odometer measures:", options:["Distance","Speed","Time","Force"], ans:0 },
    { q:"If distance is fixed, speed and time are:", options:["Directly proportional","Inversely proportional","Equal","None"], ans:1 },
    { q:"If time increases, for same distance speed:", options:["Increases","Decreases","Same","Zero"], ans:1 },
    { q:"If speed=20 km/h, distance=60 km, time=", options:["1 h","2 h","3 h","4 h"], ans:2 },
    { q:"If distance=90 km, speed=45 km/h, time=", options:["1 h","2 h","3 h","4 h"], ans:1 },
    { q:"If time=4 h, speed=25 km/h, distance=", options:["50","75","100","125"], ans:2 },
    { q:"If speed=30 km/h, time=1.5 h, distance=", options:["30","35","40","45"], ans:3 },
    { q:"If distance=150 km, time=5 h, speed=", options:["20","25","30","35"], ans:2 },
    { q:"If speed=12 m/s, in 10 s distance=", options:["12","60","120","240"], ans:2 },
    { q:"If distance=500 m, time=50 s, speed=", options:["5 m/s","10 m/s","15 m/s","20 m/s"], ans:1 },
    { q:"Speed unit (SI):", options:["m/s","km/h","cm/s","all"], ans:0 },
    { q:"Time unit (SI):", options:["Second","Minute","Hour","Day"], ans:0 },
    { q:"Distance unit (SI):", options:["Meter","Km","Cm","All"], ans:0 },
    { q:"If speed is zero, object is:", options:["Moving","At rest","Flying","Melting"], ans:1 }
  ],

  "Math (Fractions)": [
    { q:"1/2 of 10 =", options:["2","3","5","10"], ans:2 },
    { q:"1/4 of 20 =", options:["2","4","5","10"], ans:2 },
    { q:"3/5 of 50 =", options:["20","25","30","35"], ans:2 },
    { q:"2/3 of 12 =", options:["6","8","10","12"], ans:1 },
    { q:"5/6 of 60 =", options:["40","45","50","55"], ans:2 },
    { q:"1/8 of 64 =", options:["4","6","8","10"], ans:2 },
    { q:"Convert 0.25 to fraction:", options:["1/2","1/3","1/4","2/5"], ans:2 },
    { q:"Convert 0.5 to fraction:", options:["1/4","1/2","2/3","3/4"], ans:1 },
    { q:"Which is greater?", options:["1/2","1/3","1/4","1/5"], ans:0 },
    { q:"Add: 1/2 + 1/2 =", options:["1/2","1","2","0"], ans:1 },
    { q:"Subtract: 3/4 - 1/4 =", options:["1/4","1/2","2/4","3/4"], ans:1 },
    { q:"Simplify: 2/4 =", options:["1/2","2/2","4/2","1/4"], ans:0 },
    { q:"Simplify: 6/9 =", options:["1/3","2/3","3/2","2/9"], ans:1 },
    { q:"Multiply: 1/2 × 1/4 =", options:["1/6","1/8","1/4","2/8"], ans:1 },
    { q:"Divide: (1/2) ÷ (1/4) =", options:["1/8","2","4","1/2"], ans:1 },
    { q:"1/3 of 30 =", options:["5","10","15","20"], ans:1 },
    { q:"2/5 of 100 =", options:["20","30","40","50"], ans:2 },
    { q:"3/8 of 40 =", options:["10","15","20","25"], ans:0 },
    { q:"Which equals 0.75?", options:["1/4","1/2","3/4","2/3"], ans:2 },
    { q:"Which is improper fraction?", options:["3/5","5/3","1/2","2/7"], ans:1 },
    { q:"Mixed number of 7/2:", options:["3 1/2","2 1/2","1 3/2","3 2/1"], ans:0 },
    { q:"2 1/2 as improper fraction:", options:["5/2","2/5","3/2","6/2"], ans:0 },
    { q:"Common denominator for 1/2 and 1/3:", options:["5","6","8","9"], ans:1 },
    { q:"Add: 1/3 + 1/6 =", options:["1/2","2/3","1/3","5/6"], ans:0 },
    { q:"Subtract: 5/6 - 1/3 =", options:["1/6","1/2","2/3","4/6"], ans:1 },
    { q:"Simplify: 10/20 =", options:["1/2","2/5","1/4","3/4"], ans:0 },
    { q:"Which is smallest?", options:["1/2","1/3","1/4","1/5"], ans:3 },
    { q:"If 1/2 = 0.5 then 1/4 =", options:["0.2","0.25","0.4","0.75"], ans:1 },
    { q:"If a pizza has 8 slices, 3 slices =", options:["3/8","1/3","3/4","8/3"], ans:0 },
    { q:"Fraction of 2 out of 10 =", options:["1/2","1/5","2/5","1/10"], ans:1 }
  ]

};

